YAAS/YAAS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from yaasApp.rest_views import auction_search_api, bid_api
from yaasApp.views import *


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'YAAS.views.home', name='home'),

    url(r'^register/$', register),

    url(r'^signin/$', sign_in),

    url(r'^logout/$', sign_out),

    url(r'^home/$', show_home),

    url(r'^$', show_home),

    url(r'^profile/$', show_profile),

    url(r'^editprofile/$', edit_profile),

    url(r'^changepassword/$', change_password),

    url(r'^createauction/$', create_auction),

    url(r'^saveauction/$', save_auction),

    url(r'^editauction/(?P<a_id>\d+)$', edit_auction),

    url(r'^banauction/(?P<a_id>\d+)$', ban_auction),

    url(r'^auction/(?P<a_id>\d+)$', show_auction),

    url(r'^createbid/(?P<a_id>\d+)$', create_bid),

    url(r'^savebid/$', save_bid),

    url(r'^search/$', search),

    url(r'^api/v1/search/$', auction_search_api),
    url(r'^api/v1/createbid/(?P<pk>\d+)$', bid_api),

    url(r'^results/$', search_result_pagination),
    url(r'^browse/$', browse_result_pagination),

    url(r'^selectlang/(?P<lang>\w{2})$', select_lang),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

YAAS/yaasApp/forms.py
__author__ = 'stephaneki'
from django import forms

from yaasApp.models import *

MINIMUM_AUCTION_DURATION_IN_SECONDS = 72 * 60 * 60  # 72 Hours


class EditProfileForm(forms.ModelForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ('email',)


class AuctionCreationForm(forms.Form):
    title = forms.CharField(label='Title', max_length=30, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                        'placeholder': 'New auction'}))

    description = forms.CharField(label='Description', required=False,
                                  widget=forms.Textarea(attrs={'class': 'form-control'}))

    creation_date = forms.DateTimeField(widget=forms.HiddenInput, initial=timezone.now())
    deadline = forms.DateTimeField(label="Deadline",
                                   help_text="Format: YYYY-mm-dd HH:mm:ss | Deadline should be at least"
                                             " 72h after creation",
                                   widget=forms.TextInput()
                                   )
    minimum_price = forms.FloatField(label='Minimum price', min_value=0,
                                     widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_deadline(self):
        creation = self.cleaned_data.get('creation_date')
        deadline = self.cleaned_data.get('deadline')
        delta = deadline - creation
        if creation and deadline:
            if delta.total_seconds() < MINIMUM_AUCTION_DURATION_IN_SECONDS:
                raise forms.ValidationError("Deadline should be at least 72h after creation.")
        return deadline


class BidCreationForm(forms.Form):
    auction_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    price = forms.FloatField(label='Minimum price', min_value=0)

    def clean_price(self):
        price = self.cleaned_data.get('price')
        auction_id = self.cleaned_data.get('auction_id')
        auction = Auction.objects.filter(id=auction_id)[0]
        minimum_bid_price = auction.minimum_bid_price()
        if price < minimum_bid_price:
            raise forms.ValidationError("The bid must be superior to the minimum price")
        return price


class ConfirmationForm(forms.Form):
    CHOICES = [(x, x) for x in ("Yes", "No")]
    option = forms.ChoiceField(choices=CHOICES)

YAAS/templates/auction.html
{% extends "base2.html" %}
{% load i18n %}
{% block title %}
    Auction
{% endblock %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}

{% block content %}
{% if error %}
<div class="alert alert-danger">
        <span class="glyphicon glyphicon-remove"></span>
        <strong> Error! {{ error }}</strong>
</div>
{% endif %}
    <h2>{% trans "Title" %}</h2>
    <p>{{ auction.title }}</p>

    <h2>{% trans "Description" %}</h2>
    <p>{{ auction.description }}</p>

    <h2>{% trans "State" %}</h2>
    <p>{{ auction.get_state_label }}</p>

    <h2>Deadline</h2>
    <p>{{ auction.deadline }}</p>

    <h2>Minimum price</h2>
    <p>{{ auction.minimum_price }}</p>

    <h2>Seller</h2>
    <p>{{ auction.seller.username }}</p>

    <h2>Last bid</h2>
    <p>{{ last_bid }}</p> <br>

    <a class="btn btn-lg btn-primary btn-block" href="/createbid/{{ auction.id }}"> Bid for this auction </a>
    {% if can_ban %}
    <a class="btn btn-lg btn-danger btn-block" href="/banauction/{{ auction.id }}"> Ban </a>
    {% endif %}
    <br>
{% endblock %}

YAAS/templates/browse_results.html
{% extends "base2.html" %}
{% load staticfiles %}
{% block style %}
    <link rel="stylesheet" href="{% static 'signin.css' %}">
{% endblock %}

{% block title %}Search results{% endblock %}

{% block content %}

{% if error %}
    <div class="alert alert-danger">
        <span class="glyphicon glyphicon-remove"></span>
        <strong> {{ error }}</strong>
</div>
{% endif %}

   <table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Seller</th>
            <th>Deadline</th>
            <th>Minimum price</th>
            <th>Last bid</th>
            <th>State</th>
        </tr>
    </thead>
    <tbody>

    {% for auction in auctions %}
        <tr>
            <td>{{ auction.id }}</td>
            <td><a href="/auction/{{ auction.id }}">{{ auction.title }}</a></td>
            <td>{{ auction.seller.username }}</td>
            <td>{{ auction.deadline }}</td>
            <td>{{ auction.minimum_price }}</td>
            <td>{{ auction.last_bid_price }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if auctions.has_previous %}
            <a href="/browse/?page={{ auctions.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ auctions.number }} of {{ auctions.paginator.num_pages }}.
        </span>

        {% if auctions.has_next %}
            <a href="/browse/?page={{ auctions.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}

YAAS/templates/changepassword.html
{% extends "base2.html" %}

{% block title %}Change password{% endblock %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}


{% block content %}

<h2>Change password</h2>

    <form action="" method="post">
        {% csrf_token %}
         {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

YAAS/templates/confbid.html
{% extends "base2.html" %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}

{% block content %}

    {% if message %}
    <div class="alert alert-danger">
            <span class="glyphicon glyphicon-remove"></span>
            <strong> Error! {{ message }}</strong>
    </div>
    {% endif %}

    <h1>Confirm Bid</h1>
    <h2>Auction title : {{auction_title}}</h2>
    <label for="id_desc"> Description </label>
    <textarea id="id_desc" readonly cols="40" rows="5"> {{auction_desc}}</textarea>


    <form action="/savebid/" method="post">
        {% csrf_token %}
         {{ form.as_p }}
        <button class="btn btn-lg btn-primary" type="submit">Confirm</button>
    </form>
{% endblock %}

YAAS/templates/confirmation.html
{% extends "base2.html" %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}

{% block content %}

<h2>Confirm auction creation</h2>

<h2>Auction title : {{auction_title}}</h2>
<h2>Description</h2>
<p> {{ auction_desc }}</p>

<h2>Minimum price</h2>
<p> {{ auction_min_price }}</p>

<h2>Deadline</h2>
<p> {{ auction_deadline }}</p>

    <form action="/saveauction/" method="post">
        {% csrf_token %}
         {{ form.as_p }}
        <button class="btn btn-lg btn-primary" type="submit">Confirm</button>
    </form>

{% endblock %}

YAAS/templates/createauction.html
{% extends "base2.html" %}
{% load staticfiles %}


{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}

{% block style %}
      <link rel="stylesheet" href="{% static 'bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block script %}
    <script src="{% static 'bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}

{% block content %}
<h1>Create a new auction</h1>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <span class="glyphicon glyphicon-remove"></span>
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <span class="glyphicon glyphicon-remove"></span>
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}





    <form action="/createauction/" method="post" role="form">
        {% csrf_token %}
        <!--<div class="form-group">
        {{ form.title.errors }}
        {{ form.title.label_tag }}
        {{ form.title }}
        {{ form.title.help_text }}
        </div>

        <div class="form-group">
        {{ form.description.errors }}
        {{ form.description.label_tag }}
        {{ form.description }}
        {{ form.description.help_text }}
         </div>

         <div class="form-group">
         {{ form.deadline.label_tag }}
         {{ form.deadline }}
         {{ form.deadline.help_text }}
         </div>

         <div class="form-group">
        {{ form.minimum_price.errors }}
        {{ form.minimum_price.label_tag }}
        {{ form.minimum_price }}
        {{ form.minimum_price.help_text }}
        </div> -->

        {{ form.as_p }}

        <button class="btn btn-lg btn-primary" type="submit">Create</button>
    </form>







{% endblock %}

YAAS/templates/createbid.html
{% extends "base2.html" %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}

{% block content %}
<h1>Create Bid</h1> <br>
{% if error %}
<div class="alert alert-danger">
        <span class="glyphicon glyphicon-remove"></span>
        <strong> Error! {{ error }}</strong>
</div>
{% endif %}
    <h2>Minimum bid : {{minimum_bid}}</h2>
    <form action="/createbid/{{ auction_id }}" method="post">
        {% csrf_token %}
         {{ form.as_p }}
        <button class="btn btn-lg btn-primary" type="submit">Create</button>
    </form>

{% endblock %}

YAAS/templates/done.html
{% extends 'base2.html' %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}


{% block content %}

<h1> Thanks.</h1> <br>

{% if message %}
 {{ message }}
{% endif %}
<br>

You may proceed to <a href="/home/"> Homepage</a>.


{% endblock %}

YAAS/templates/editauction.html
{% extends "base2.html" %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}


{% block content %}
<p><b>Edit Auction</b></p>
  {% if error%}
  <p> <b>{{ error }}</b> </p>
    {% endif %}

    <form action="/editauction/{{ auction.id }}" method="post">
        {% csrf_token %}

        <p>
        <label for="id_title">Title</label>
        <input readonly id="id_title" type="text" value="{{ auction.title }}">
        </p>

        <p>
        <label for="id_description"> Description: </label>
        <textarea id="id_description" name="description" cols="35" rows="10">{{ auction.description }} </textarea>
        </p>

        <input type="submit" value="Save">
    </form>

{% endblock %}

YAAS/templates/editprofile.html
{% extends "base2.html" %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}


{% block title %}
    Edit profile
{% endblock %}
{% block content %}
<h1> Edit your profile </h1>
<form action="" method="post" class="form-horizontal">
        {% csrf_token %}
         {{ form.as_p }}
        <input type="submit" value="Submit">
</form>
{% endblock %}

YAAS/templates/index.html
{% extends "base2.html" %}
{% load i18n %}
{% block title %}
    YAAS - Home
{% endblock %}

{% block signin_user %}
    {% include 'navbar_signin.html' %}
{% endblock %}

{% block content %}
    {% if msg %}
        <div class="alert alert-success">
            <span class="glyphicon glyphicon-ok"></span>
            <strong> {{ msg }}</strong>
        </div>
    {% endif %}

    {% if error %}
        <div class="alert alert-danger">
            <span class="glyphicon glyphicon-remove"></span>
            <strong> Error! {{ error }}</strong>
        </div>
    {% endif %}


    <table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>{% trans "Title" %}</th>
            <th>{% trans "Seller" %}</th>
            <th>{% trans "Deadline" %}</th>
            <th>{% trans "Minimum price" %}</th>
            <th>{% trans "Last bid" %}</th>
            <th>{% trans "State" %}</th>
        </tr>
    </thead>
    <tbody>

    {% for auction in auctions %}
        <tr>
            <td>{{ auction.id }}</td>
            <td><a href="/auction/{{ auction.id }}">{{ auction.title }}</a></td>
            <td>{{ auction.seller.username }}</td>
            <td>{{ auction.deadline }}</td>
            <td>{{ auction.minimum_price }}</td>
            <td>{{ auction.last_bid.price }}</td>
            <td>{{ auction.get_state_label }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>




    <br>
{% endblock %}

YAAS/templates/navbar_signin.html
    {% if username %}
        <li class="dropdown" >
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-user"></span> {{ username }}
            <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="/profile/">Profile</a></li>
                <li><a href="/logout/">Sign out</a></li>
                <li><a href="/changepassword/">Change password</a></li>
                <li><a href="/createauction/">Create auction</a></li>
            </ul>
        </li>
    {% else %}
        <li ><a href="/signin/"> <span class="glyphicon glyphicon-user"></span> Sign in</a></li>
    {% endif %}

YAAS/templates/registration.html
{% extends "base2.html" %}

{% block title %}Create User{% endblock %}

{% block content %}

<h2>Create an account</h2>

    <form action="" method="post">
        {% csrf_token %}
         {{ form.as_p }}
        <input type="submit" value="Register">
    <p>You already have an account? <a href="/signin/"> Sign in now</a> </p>
    </form>

{% endblock %}

YAAS/templates/signin.html
{% extends "base2.html" %}
{% load staticfiles %}
{% block style %}
    <link rel="stylesheet" href="{% static 'signin.css' %}">
{% endblock %}
{% block content %}

  {% if form.errors%}
    <p> Password or username is incorrect </p>
  {% endif %}

    <form action="" method="post" class="form-signin" role="form">
        {% csrf_token %}
        <h2 class="form-signin-heading">{{ error }}</h2>
        <input class="form-control" type="text" name="username" value="" id="username" placeholder="Username">
        <input class="form-control" type="password" name="password" value="" id="password" placeholder="Password">

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

        <p> New to YAAS ? Get started now: <a href="/register/">register</a> </p>
    </form>


{% endblock %}